### ISSUE TITLE
Patched

### ISSUE THREAD

**Issue by owersite** [danielkrupinski/OneByteQuickDuck#3]
Quick Duck Patched

**Comment by danielkrupinski** [comment]
Nope

**Comment by owersite** [comment]
It is

**Comment by owersite** [comment]
I'm opening the app and pymem shows program closes i go back to game and i just cannot quick duck :/

**Comment by danielkrupinski** [comment]
Change `client_panorama.dll` in source code to `client.dll`. You have to hold walk key (shift) in order to make it work.
